import {NextResponse} from 'next/server';
import OpenAI from 'openai';
import mammoth from 'mammoth';
import fs from 'node:fs/promises';
import path from 'node:path';
export const runtime='nodejs';
export const dynamic='force-dynamic';
export const maxDuration=60;
const shows=['Beggar Husband','Billionaire Hidden Wife','Brahmand Ka Rakshak','Brahmyodha: The Destroyer','Divine Flame Burst','Divine Power','Ek Stranger Se Pyar','Empire of Hidden King','Fated To Be Yours','His Secret Fortune','King of Dragon','Malang','Married To a Hard Hearted','My Mysterious Princess','Primordial God','Purple Thunder Sovereign','Rudra: Rise of the Supreme Yodha','Ruthless','Shiva: Ek Pretyodha','The Legend Gods','The Warrior'];
const rubric=`Return JSON only. Evaluate with TWO INDEPENDENT score columns: ruleScores and patternScores. ruleScores judge only the authoritative rule-set. patternScores judge only learned observations from successful promo benchmarks. Score 9 parameters 1-10: Hook, Context & World Clarity, Sequence & Plot Movement, Scene Design, Pacing & Transitions, Ending, Callback & CTA, Narration/Dialogue Balance, Mental Impact & Recall Value, Follow successful promos pattern. Calculate ruleFinalScore and patternFinalScore separately using: Hook*.20 + Context*.10 + Sequence*.10 + Scene*.15 + Pacing*.10 + Ending*.10 + Follow pattern*.15 + Mental Impact*.15. Return both tiers (P0 >=8.5, P1 >=6.5, P2 below), finalScore=patternFinalScore, patternCategoryMatch, fidelity, summary, strengths, problems, suggestions, evidence, structure, contradictions. For every parameter below 7 in either column return exactly five suggestions with approach, rewrite, reason. Never invent source evidence.`;
async function readDoc(file:string){return (await mammoth.extractRawText({buffer:await fs.readFile(file)})).value}
async function context(show:string){const root=process.cwd();const sd=path.join(root,'Show Content');const wd=path.join(root,'Winning Promo Scripts');const norm=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]/g,'');const key=norm(show).slice(0,12);const sf=(await fs.readdir(sd).catch(()=>[])).find(f=>f.endsWith('.docx')&&norm(f).includes(key));const aliases:Record<string,string[]>={'king of dragon':['kod'],'my mysterious princess':['mmp','mmps'],'the warrior':['twar'],'beggar husband':['bh'],'billionaire hidden wife':['bhw','bhy'],'divine power':['dp'],'divine flame burst':['dfb'],'fated to be yours':['ftby'],'his secret fortune':['hsf'],'malang':['ml'],'primordial god':['pg'],'purple thunder sovereign':['pts'],'ruthless':['rl'],'the legend gods':['tlg'],'empire of hidden king':['ehk'],'ek stranger se pyar':['essp'],'brahmand ka rakshak':['bkr'],'brahmyodha: the destroyer':['brhw'],'shiva: ek pretyodha':['stdl']};const codes=aliases[show.toLowerCase()]||[key];const wf=(await fs.readdir(wd).catch(()=>[])).filter(f=>codes.some(c=>f.toLowerCase().startsWith(c))).slice(0,12);return {source:sf?await readDoc(path.join(sd,sf)):'',benchmarks:(await Promise.all(wf.map(f=>readDoc(path.join(wd,f))))).join('\n--- BENCHMARK ---\n'),sourceFile:sf,winFiles:wf}}
export async function POST(req:Request){try{const b=await req.json();if(!b.name||!b.script)return NextResponse.json({error:'Name and promo script are required.'},{status:400});if(!shows.includes(b.show))return NextResponse.json({error:'Please select a valid show.'},{status:400});const key=process.env.OPENROUTER_API_KEY?.trim()||process.env.OPENAI_API_KEY?.trim();if(!key)return NextResponse.json({error:'No API key found in Production variables.'},{status:500});const c=await context(b.show);const model=(process.env.OPENROUTER_MODEL||process.env.OPENAI_MODEL||'gpt-4o-mini').trim();const baseURL=(process.env.OPENROUTER_BASE_URL||process.env.OPENAI_BASE_URL||'https://openrouter.ai/api/v1').trim();const prompt=`${rubric}\nSHOW SOURCE (${c.sourceFile||'not found'}):\n${c.source.slice(0,80000)}\nSUCCESSFUL BENCHMARKS (${c.winFiles.length}):\n${c.benchmarks.slice(0,100000)}\nUSER PROMO A:\n${b.script}\n${b.mode==='compare'?`USER PROMO B:\n${b.second}`:''}`;const out=await new OpenAI({apiKey:key,baseURL}).chat.completions.create({model,messages:[{role:'system',content:'You are an expert PocketFM promo editor. Use only supplied source and benchmarks.'},{role:'user',content:prompt}],response_format:{type:'json_object'}});return NextResponse.json(JSON.parse(out.choices[0].message.content||'{}'))}catch(e){console.error('evaluation_error',e instanceof Error?e.message:'unknown');return NextResponse.json({error:'Evaluation is unavailable. Check the server API configuration.'},{status:500})}}
