'use client';
import {useState} from 'react';

const shows=['Beggar Husband','Billionaire Hidden Wife','Brahmand Ka Rakshak','Brahmyodha: The Destroyer','Divine Flame Burst','Divine Power','Ek Stranger Se Pyar','Empire of Hidden King','Fated To Be Yours','His Secret Fortune','King of Dragon','Malang','Married To a Hard Hearted','My Mysterious Princess','Primordial God','Purple Thunder Sovereign','Rudra: Rise of the Supreme Yodha','Ruthless','Shiva: Ek Pretyodha','The Legend Gods','The Warrior'];
const genres=['Fantasy','Drama','Horror'];
type Result={ruleScores:Record<string,number>;patternScores:Record<string,number>;finalScore:number;tier:string;fidelity:number;summary:string;strengths:string[];problems:string[];suggestions:Record<string,{approach:string;rewrite:string;reason:string}[]>;evidence:string[];structure:string;contradictions:string[]};
export default function Home(){const [name,setName]=useState('');const [show,setShow]=useState(shows[10]);const [genre,setGenre]=useState('Fantasy');const [script,setScript]=useState('');const [mode,setMode]=useState<'single'|'compare'>('single');const [second,setSecond]=useState('');const [loading,setLoading]=useState(false);const [result,setResult]=useState<Result|null>(null);const [error,setError]=useState('');
 async function evaluate(){setError('');setLoading(true);try{const r=await fetch('/api/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,show,genre,script,second,mode})});const j=await r.json();if(!r.ok)throw Error(j.error);setResult(j)}catch(e){setError(e instanceof Error?e.message:'Evaluation failed')}finally{setLoading(false)}}
 const wordCount=script.trim()?script.trim().split(/\s+/).length:0;
 return <main><nav><div className="brand"><span className="mark">P</span><span>Pocket<span>FM</span></span><small>PROMO LAB</small></div><div className="profile">{name?`Hi, ${name}`:'Script evaluator'} <span className="avatar">{name?.[0]?.toUpperCase()||'U'}</span></div></nav>
 <section className="hero"><div><p className="eyebrow">AI-POWERED STORY INTELLIGENCE</p><h1>Make every promo<br/><i>impossible to ignore.</i></h1><p className="lede">Get a source-grounded score, sharp creative diagnosis, and five actionable rewrites for every weak area.</p></div><div className="orb"><span>✦</span></div></section>
 <section className="workspace"><div className="panel form"><div className="step"><b>01</b><div><label>Your name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="How should we call you?"/></div></div><div className="step"><b>02</b><div className="grid"><div><label>Show</label><select value={show} onChange={e=>setShow(e.target.value)}>{shows.map(s=><option key={s}>{s}</option>)}</select></div><div><label>Genre</label><select value={genre} onChange={e=>setGenre(e.target.value)}>{genres.map(s=><option key={s}>{s}</option>)}</select></div></div></div><div className="mode"><button className={mode==='single'?'active':''} onClick={()=>setMode('single')}>Single promo</button><button className={mode==='compare'?'active':''} onClick={()=>setMode('compare')}>Compare two</button></div><div className="step"><b>03</b><div className="grow"><label>Promo script A <span>{wordCount} words</span></label><textarea value={script} onChange={e=>setScript(e.target.value)} placeholder="Paste your promo script here…"/><label className="upload">↥ Upload .docx <input type="file" accept=".docx,.txt" onChange={async e=>{const f=e.target.files?.[0];if(f)setScript(await f.text())}}/></label></div></div>{mode==='compare'&&<div className="step"><b>04</b><div className="grow"><label>Promo script B</label><textarea value={second} onChange={e=>setSecond(e.target.value)} placeholder="Paste the second promo…"/></div></div>}<button className="evaluate" disabled={loading||!script||!name} onClick={evaluate}>{loading?'Reading source + benchmarks…':'Evaluate promo  →'}</button>{error&&<p className="error">{error}</p>}<p className="privacy">Your script is evaluated privately. API keys never reach the browser.</p></div>
 <div className="panel result">{!result?<div className="empty"><div className="spark">✦</div><h2>Your creative report<br/>will appear here.</h2><p>Select a show and paste a promo to begin.</p><div className="chips"><span>Source fidelity</span><span>Pattern learning</span><span>5 refreshes / weak area</span></div></div>:<Report r={result}/>}</div></section></main>}
 function Report({r}:{r:Result}){const names=Object.keys(r.ruleScores);return <div className="report"><div className="reportHead"><div><p className="eyebrow">EVALUATION COMPLETE</p><h2>{r.tier} <span>· {r.finalScore.toFixed(1)}/10</span></h2></div><div className="fidelity"><strong>{r.fidelity}%</strong><small>source fidelity</small></div></div><p className="summary">{r.summary}</p><div className="scores">{names.map(n=><div className="score" key={n}><small>{n}</small><strong>{r.ruleScores[n].toFixed(1)}</strong><em>rule</em><b>{r.patternScores[n].toFixed(1)} pattern</b></div>)}</div><div className="columns"><div><h3>What’s working</h3>{r.strengths.map(x=><p className="good" key={x}>✓ {x}</p>)}<h3>Source evidence</h3>{r.evidence.map(x=><p key={x}>◈ {x}</p>)}</div><div><h3>Priority fixes</h3>{r.problems.map(x=><p className="bad" key={x}>! {x}</p>)}{r.contradictions.length>0&&<><h3>Contradictions</h3>{r.contradictions.map(x=><p className="bad" key={x}>{x}</p>)}</>}<h3>Detected structure</h3><p>{r.structure}</p></div></div><h3>Refresh suggestions</h3>{Object.entries(r.suggestions).map(([k,arr])=><details key={k}><summary>{k} <span>5 options</span></summary>{arr.map((s,i)=><div className="suggestion" key={i}><b>{i+1}. {s.approach}</b><p>{s.rewrite}</p><small>{s.reason}</small></div>)}</details>)}</div>}
